### ISSUE TITLE
Node.js doesn't support windows 7 anymore

### ISSUE THREAD

**Issue by Midou36O** [terrific-tea/teabrowse#93]
I don't know if the browser would work at all on 7 (like my pc), i'll try and see if i can find a workaround it and if it actually ignores the limitation when built.

**Comment by Rexogamer** [comment]
Wait, for real?

**Comment by Midou36O** [comment]
![image](https://user-images.githubusercontent.com/45198486/101087998-510a9c00-35b3-11eb-994c-4edb6d3e09c0.png)
yup

**Comment by Oxygemo** [comment]
I told you to ditch Windows 7

**Comment by Rexogamer** [comment]
7 has been EOL for a while. If you want Windows, upgrade to 10; else just use Linux. Closing this as this is realistically a Node issue.
